// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    Create: typeof import('./components/customer/Create.vue')['default']
    Edit: typeof import('./components/customer/Edit.vue')['default']
    EpArrowDownBold: typeof import('~icons/ep/arrow-down-bold')['default']
    EpArrowUpBold: typeof import('~icons/ep/arrow-up-bold')['default']
    EpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    List: typeof import('./components/customer/List.vue')['default']
    Show: typeof import('./components/customer/Show.vue')['default']
  }
}

export { }
