// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EpArrowDownBold: typeof import('~icons/ep/arrow-down-bold')['default']
    EpArrowUpBold: typeof import('~icons/ep/arrow-up-bold')['default']
    EpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
  }
}

export { }
